services:
  - type: web
    name: proaccdb-app
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: PORT
        value: "3000"
      - key: DB_SERVER
        fromService:
          name: proaccdb-app
          envVarKey: DB_SERVER
      - key: DB_DATABASE
        fromService:
          name: proaccdb-app
          envVarKey: DB_DATABASE
      - key: DB_USER
        fromService:
          name: proaccdb-app
          envVarKey: DB_USER
      - key: DB_PASSWORD
        fromService:
          name: proaccdb-app
          envVarKey: DB_PASSWORD
      - key: DB_INSTANCE
        fromService:
          name: proaccdb-app
          envVarKey: DB_INSTANCE
      - key: DB_ENCRYPT
        value: "true"
